permalink:  /:title/
url: 'https://thefutureiswork.com'
remoteAssetUrl: https://s3.amazonaws.com/thefutureiswork.com/

# Title tag variables
title: The Future is Work
description: |
  An [open source](/) journal and compendium about working in the digital era!

# Other external links
analytics_tracking_id: "UA-86377416-3"

# Misc variables
highlighter: 'rouge'
encoding: utf-8

# Number of posts on each page.
paginate: 20
paginate_path: "/:num/"
var_older: 'Next'
var_newer: 'Previous'

# External resources
plugins: 
  - jekyll-paginate
exclude:
  - hyde

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /:title/
